### PR TITLE
feat: added telegram proxy in CLI

### PR DESCRIPTION
**Pull request by IgnatovFedor**
#426

### CODE REVIEW

**Comment by acriptis** [comment]
А почему у нас женкинс падает?
http://dev.ipavlov.mipt.ru:8080/blue/organizations/jenkins/DeepPavlov/detail/PR-1217/18/pipeline

**Comment by acriptis** [comment]
[2020-07-08T12:43:48.276Z]   WARNING: Building wheel for deeppavlov failed: [Errno 28] No space left on device

**Comment by IgnatovFedor** [comment]
Closed due to end of [blocking Telegram in Russia](https://rkn.gov.ru/news/rsoc/news73050.htm)

**Comment by IgnatovFedor** [comment]
Closed due to end of [blocking Telegram in Russia](https://rkn.gov.ru/news/rsoc/news73050.htm)

**Pull request closed without merging**
