### PR TITLE
fix: issue#1230

### LINKED ISSUE #1230: Data set creation routine for gobot DSTC 2 format
Hi,

I want to create data set creation routine for gobot DSTC 2 format. I know that that there is an on going refactoring of the codebase for the Goal-oriented bot (gobot). 

Also, there is a new DSTC 8 challenge and Alexa Prize socialbot which is to be open sourced.

So I want to ask if this feature would be needed or is it duplication of work? 

Ideally, I want to pull the routine to the deeppavlov repo, so I need some guidance/advice before jumping into the implementation.

Things I want to clarify:

1) Is this routine needed to be developed? Or is it already underway and it would be duplication of work? 
2) What format would be best (DSTC 2 json, DSTC 8, etc)?
3) I want to create CLI with python, is it good?

Anything else you think might be appropriate.

### PR DESCRIPTION
**Pull request by Eugen2525**
resolves #1230

### CODE REVIEW

**Comment by Eugen2525** [comment]
why does continuous-integration not pass? what is wrong?

I did not modify any existing file, just added new two. Could someone explain how to pass this?

**Comment by yoptar** [comment]
> why does continuous-integration not pass? what is wrong?
> 
> I did not modify any existing file, just added new two. Could someone explain how to pass this?

Tests fail on other modules, please don't mind them for now.

**Comment by oserikov** [comment]
Hey! I just checked out and played a bit.

Could you provide sample files (e.g. `dstc2-templates.txt`) to make the example notebook work via run all for these users who could be not that familiar with the notebook?

I suggest you to use the [%%writefile](https://ipython.readthedocs.io/en/stable/interactive/magics.html#cellmagic-writefile) command to ship the missing files via notebook

**Comment by Eugen2525** [comment]
> 
> 
> Hey! I just checked out and played a bit.
> 
> Could you provide sample files (e.g. `dstc2-templates.txt`) to make the example notebook work via `run all` for these users who could be not that familiar with the notebook?
> 
> I suggest you to use the [%%writefile](https://ipython.readthedocs.io/en/stable/interactive/magics.html#cellmagic-writefile) command to ship the missing files via notebook

Thanks, which folder do  you want me to put the input files? 

in the `DeepPavlov/examples/` folder?

**Comment by oserikov** [comment]
See [my pr](https://github.com/Eugen2525/DeepPavlov/pull/1) for the contrib section, I think contrib/examples is ok

**Comment by Eugen2525** [comment]
> See [my pr](https://github.com/Eugen2525/DeepPavlov/pull/1) for the contrib section, I think contrib/examples is ok :)

Thanks for the contribution and also for refactoring. I have added the missing files, I hope it is fine now ))

**Comment by oserikov** [comment]
thx! I'll review this tonight

**Comment by oserikov** [comment]
Hey! Cool, now we have everything the tool needs kept in the repo.

[Here is the notebook](https://colab.research.google.com/github/Eugen2525/DeepPavlov/blob/ds_generation_branch/deeppavlov/contrib/examples/Dataset_generation_tutorial.ipynb) I tried to run via Runtime->Run all   
(except for the deeppavlov was installed with `!pip install git+https://github.com/Eugen2525/DeepPavlov.git@ds_generation_branch` but that's a regular hack). 

It failed because the paths in the notebook do lead to nowhere.

[This is how I fixed](https://colab.research.google.com/drive/1jvt-oGvvoAHOKH8WppghgHcY97r8xl3V?usp=sharing) errors (see 2nd cell). If you find this an OK solution, then it's just add smth like this to the example notebook. Other ways to handle this are ok too. 

I mean, the goal is to allow for users to just open the notebook via e.g. colab and have *everything* working out-of-the-box. Like I just opened the notebook and used Run all cells.

---

Another small suggestion is to start the user's prompt from the new line, that's easier when one has not that wide screen. **But that's clearly a matter of taste** -- I'm ok with the way things are working now.

---

I have no other comments: the code looks OK and the stuff works. 
**We'll need a README** (I think that it's OK to write the small helping doc just in beginning of the example.ipynb). Me, I'm ok with merge just right after the run-all way will start working without errors.

**Comment by Eugen2525** [comment]
@oserikov Thanks for your feedback, I have added the missing parts and fixes. It went smooth with Colab too and hope it is good now.

I will improve it a little later and include a tutorial to create a new dataset on a completely new domain later. That's my plan at least ))

**Comment by oserikov** [comment]
Ok. So you want me to wait for these improvements?

**Comment by Eugen2525** [comment]
> Ok. So you want me to wait for these improvements?

nope, as I do not know when that will be done. What I said is just a plan I hope to do in some near future.

Please go ahead with the finalization of this PR.

**Comment by Eugen2525** [comment]
> 
> 
> Ok. So you want me to wait for these improvements?

Hey, you can merge already.

I do not know when exactly I will be able to make  contribute, so I please merge this :))

**Comment by oserikov** [comment]
Oh! Sorry, will review today!

**Comment by oserikov** [comment]
@Eugen2525  I [PRed](https://github.com/Eugen2525/DeepPavlov/pull/2) a small simplification to avoid `wget`ong the hardcoded files. 

Everything else seems legit to me, requesting the second review. (We require each PR to have 2 approving reviews)

**Comment by oserikov** [comment]
Hey @Eugen2525 ! BTW, is there any way to contact you? Just in case. Like.. email or social net or smth like this. Commits are linked with the `noreply` email :(

**Comment by Eugen2525** [comment]
@oserikov Sure, please use the following email 'eugen2525[at]yandex.ru'

**Pull request merged**
